---
# tasks file for webserver-n01559954
- name: Install and configure Apache web server
  apt:
    name: "{{ apache_service }}"
    state: present
  become: yes
  tags: webserver

- name: Create files with FQDN
  copy:
    content: "{{ inventory_hostname }}"
    dest: "{{ item }}"
  loop:
    - /path/to/vm1.html
    - /path/to/vm2.html
    - /path/to/vm3.html
  tags: webserver

- name: Copy files to web servers
  copy:
    src: "{{ item }}"
    dest: "{{ web_files_dir }}/index.html"
  loop:
    - /path/to/vm1.html
    - /path/to/vm2.html
    - /path/to/vm3.html
  tags: webserver

- name: Set permissions on files
  file:
    path: "{{ web_files_dir }}/index.html"
    mode: '0444'
  tags: webserver

- name: Start Apache web server
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_service_state }}"
    enabled: "{{ apache_service_enabled }}"
  become: yes
  tags: webserver